### ISSUE TITLE
Dados de sísmica e vulcanismo

### ISSUE THREAD

**Issue by juoceano** [juoceano/introductiontooceanography#3]
@ocefpaf 
- [ ] achar dados abertos de sísmica
- [ ] achar dados abertos de vulcanismo
- [ ] mapa de sísmica
- [ ] mapa de vulcanismo

**Comment by ocefpaf** [comment]
- [ ] achar dados abertos de sísmica
- [ ] achar dados abertos de vulcanismo
- [ ] mapa de sísmica
- [ ] mapa de vulcanismo

**Comment by ocefpaf** [comment]
- [ ] achar dados abertos de sísmica
- [ ] achar dados abertos de vulcanismo
- [X] mapa de sísmica
- [X] mapa de vulcanismo

You have to read the metadata to find the terms of use of that data!  (See PR #6)

**Comment by juoceano** [comment]
Os dados são da USGS e do DOI e são pra uso geral. A USGS só pede que seja dado crédito a eles: 
http://www.usgs.gov/laws/info_policies.html
When using information from USGS information products, publications, or Web sites, we ask that proper credit be given. Credit can be provided by including a citation such as the following:
Credit: U.S. Geological Survey
Department of the Interior/USGS
U.S. Geological Survey/photo by Jane Doe (if the photographer/artist is known) 

Já o DOI é mais enrolado:
http://www.doi.gov/copyright.cfm

**Comment by ocefpaf** [comment]
OK, eu chequei os dados de sísmica são "Public domain", a mesma política se aplica as dados de vulcões da NOAA: http://www.ngdc.noaa.gov/ngdcinfo/privacy.html#disclaimer
