### ISSUE TITLE
Batimetria

### ISSUE THREAD

**Issue by juoceano** [juoceano/introductiontooceanography#4]
@ocefpaf 
- [ ] batimetria Elevação de Rio Grande
- [ ] batimetria Cadeia Vitória-Trindade
- [ ] algum outro

:pig2::pig2::pig2::pig2::pig2::pig2::pig2::pig2:

**Comment by ocefpaf** [comment]
Quantos  :pig: só um já é trabalho bastante :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
All done! http://nbviewer.ipython.org/gist/ocefpaf/85ebba286769b6da1394
